// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SendRequest(arg1:main.RequestInput):Promise<main.ResponseOutput>;
